### ISSUE TITLE
do you know where is the code of tnn cpp code of yolo fastest?

### ISSUE THREAD

**Issue by henbucuoshanghai** [JunFenngZhi/YOLO-Fastest#2]
only ncnn?

**Comment by JunFenngZhi** [comment]
yes. I only implement yolo-fastest through ncnn. Maybe you can refer to tnn's documentation to implement yolo-fastest by yourself.

**Comment by henbucuoshanghai** [comment]
thanks。when you know where is the tnn code,please  tell me.
